curl -X POST http://localhost:3000/api/auth/signup \
  -H "Content-Type: application/json" \
  -d '{"username":"johndee",
  "password": "password1s23",
  "email": "johl@email.com"
  }'
###
curl -X POST http://localhost:3000/api/auth/logout \
  -H "Content-Type: application/json" \

###
curl -X POST http://localhost:3000/api/auth/login \
  -H "Content-Type: application/json" \
  -d '{"email": "johl@email.com",
  "password": "password1s23"
  }'
###
  curl -X POST http://localhost:3000/api/auth/refresh-token\
  -H "Content-Type: application/json" \
  -d '{"email": "johl@email.com",
  "password": "password1s23"
  }'
###
curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36" https://vsco.co/jessieeethomson/gallery
